version: '2'

services:
  jenkins:
    image: rescapes_jenkins
    container_name: rescapes_jenkins
    build:
      context: .
      dockerfile: ./compose/jenkins/Dockerfile
    volumes:
      - /tmp/jenkins/:/tmp/jenkins/
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/tp2/compose/jenkins/data/:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    
  master:
    image: rescapes_ionic_server
    container_name: rescapes_master
    ports:
      - "7000:7000"
    build:
      context: .
      dockerfile: ./compose/ionic_server/Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      - BRANCH=master
      - PORT=7000
      
  staging:
    image: rescapes_ionic_server
    container_name: rescapes_staging
    ports:
      - "7001:7001"
    build:
      context: .
      dockerfile: ./compose/ionic_server/Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      - BRANCH=staging
      - PORT=7001
  
  prod:
    image: rescapes_ionic_server
    container_name: rescapes_prod
    ports:
      - "7002:7002"
    volumes:
      - ~/.ssh:/root/.ssh
    build:
      context: .
      dockerfile: ./compose/ionic_server/Dockerfile
    environment:
      - BRANCH=prod
      - PORT=7002
      
  test:
    image: rescapes_test
    container_name: rescapes_test
    build:
      context: .
      dockerfile: ./compose/test_server/Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
    